linkers_website/apps/Linker/urls.py
from django.urls import path
from .views import  search_view, SearchResultsView,graph_data, multiselect,add_linker
app_name = "Linker"

urlpatterns = [
    path('search/', search_view, name='search_results'),  # Function-based view
    path('multisearch/', multiselect, name='search'),  # Function-based view
    path('search/results/', SearchResultsView.as_view(), name='search_results_list'),  # Class-based view
    path('<str:idurl>/', graph_data, name='linker_sequence'), #Function-based view 
    path('add_linker',add_linker,name="addlinker")
    
    #path('',Multiplesearchtemp),
    
 

]

linkers_website/apps/calculator/urls.py
from django.urls import path
from .views import  calc
app_name = "calculator"

urlpatterns = [
    path('', calc, name='calculator'),  # Function-based view
    #path('search/', search_view, name='search_results'),  # Function-based view
    #path('search/results/', CalcResultsView.as_view(), name='search_results_list'),
    #path('search/results/',flex_calc,name='flex_calc')
    
]

linkers_website/apps/test2/urls.py
from django.urls import path
from .views import graph_data, searchdata

app_name = "test2"

urlpatterns = [
    path('',searchdata,name='search'),
    path('graph/<str:id>/',graph_data,name='graph')
    #path('search/results/', SearchResultsView.as_view(), name='search_results')
    #path('search/', graph_data, name='results'),
]

linkers_website/apps/test3/urls.py
from django.urls import path
from .views import  search_view, SearchResultsView,graph_data, multiselect,add_linker
app_name = "test3"

urlpatterns = [
    path('search/', search_view, name='search_results'),  # Function-based view
    path('multisearch/', multiselect, name='search'),  # Function-based view
    path('search/results/', SearchResultsView.as_view(), name='search_results_list'),  # Class-based view
    path('<str:idurl>/', graph_data, name='linker_sequence'), #Function-based view 
    path('add_linker',add_linker,name="addlinker")
    
    #path('',Multiplesearchtemp),
    
 

]

linkers_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views



from . import views # to import function that directs to homepage


urlpatterns = [
    path("", include('linkers_website.apps.public.urls')),
    path("admin/", admin.site.urls),
    path("contact/", include('linkers_website.apps.contact.urls')),
    path("linkers/", include('linkers_website.apps.Linker.urls')),
    path("calculator/", include('linkers_website.apps.calculator.urls')),

]

linkers_website/apps/calculator/models.py
from django.db import models


class calc(models.Model):
    sequence=models.CharField(max_length=2000)

linkers_website/apps/contact/models.py
from django.db import models

linkers_website/apps/contact/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder': "Name"}))
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class' : 'form-control', 'placeholder': "Email"}))
    message = forms.CharField(required=True, widget=forms.Textarea(attrs={'class' : 'form-control', 'placeholder': "Message"}))

linkers_website/apps/Linker/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Linker,flexibility,Hydrophobicity
from django.http import HttpResponseRedirect
import sys  
from django.views.generic import ListView
from django.db.models import Q # new
from django.shortcuts import render
import ast
import pandas as pd
import plotly.express as px
from plotly.offline import plot
from .forms import LinkerForm,FlexForm
import json,requests
import time

import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap
import io
import base64
from PIL import Image
from io import BytesIO



# render the search_results.html template
def search_view(request):
    return render(request, 'search_results.html')


# querying the dataset
# this is for search box when user enters a string 
class SearchResultsView(ListView):
    model = Linker
    template_name = 'search_results.html'

    def get_queryset(self):
        query = str(self.request.GET.get('query'))  # get the 'query' input from the form and convert it to a string
        print("Query:", query)  # print the value of query (command line)
        if query:
            object_list = Linker.objects.filter(
                Q(id__icontains=query)
            )
        else:
            object_list = Linker.objects.none()  # return an empty queryset if no query is provided
        return object_list
    

#return the linker's information and flexibility graph
def graph_data(request,idurl):
    #search through linker database and extract information related to the linker
    linker = get_object_or_404(Linker, id=idurl)
    hydrophobicity_data = Hydrophobicity.objects.get(id=idurl)
    
    #if the length of linker is greater or equal to 5
    #perform the following function to output the flexibility graph
    if linker.length >=5:
        hydrophobicity_data = Hydrophobicity.objects.get(id=idurl)

        data_instance = flexibility.objects.get(id=idurl)
        sequence_list=data_instance.Sequence
        char_list_str = data_instance.backbone  
        #conver the list of strings to numbers
        char_list = ast.literal_eval(char_list_str)    

        #index amino acid
        index_list=[]
        for i in range(1,len(sequence_list)+1):
            index=sequence_list[i-1]+str(i)
            index_list.append(index)

        #combined the index list and backbone dynanmic into one dataframe 
        df=pd.DataFrame(list(zip(index_list,char_list)),columns=['residue index','S^2'])
        df = df.reset_index(drop=True)

        #plot
        fig=px.line(df, x='residue index', y="S^2")

        fig.update_layout(title='Backbone Dynamic',yaxis_range=[df['S^2'][0]-0.2,1])

        
        fig.add_shape(type="rect",
                x0=df['residue index'][0], y0=0.69,
                x1=df['residue index'][len(df)-1], y1=0.8,
                fillcolor='rgba(0, 255, 0, 0.3)',
                line=dict(color='rgba(0, 0, 0, 0)'))

        # Add the annotation outside the graph
        fig.add_annotation(
            xref='paper', x=0,  # Position the annotation outside the left side of the graph
            yref='paper', y=1,  # Position the annotation at the top of the graph
            text="Rigid",  # Text of the annotation
            showarrow=False,  # Hide the arrow
            font=dict(color='black', size=15)  # Font style
        )

        # Add the annotation outside the graph
        fig.add_annotation(
            xref='paper', x=0,  # Position the annotation outside the left side of the graph
            yref='paper', y=0,  # Position the annotation at the top of the graph
            text="Flexible",  # Text of the annotation
            showarrow=False,  # Hide the arrow
            font=dict(color='black', size=15)  # Font style
        )

        # Add the annotation outside the graph
        fig.add_annotation(
            x=index_list[1],  # Position the annotation outside the left side of the graph
            y=0.75,  # Position the annotation at the top of the graph
            text="Context Dependent",  # Text of the annotation
            showarrow=False,  # Hide the arrow
            font=dict(color='black', size=15)  # Font style
        )

        #pass to the template
        dynamic_plot=plot(fig, output_type="div")
        context={
            'plot_dyna':dynamic_plot,
            'linker': linker,
            'hydrophobicity_data': hydrophobicity_data
            }
        return render(request,'linker_details.html', context)
    else:
        hydrophobicity_data = Hydrophobicity.objects.get(id=idurl)
        
        context={
            'linker': linker,
            'hydrophobicity_data': hydrophobicity_data
            }
        return render(request, 'linker_details.html', context)

 
def lengthselect(length_selection):
    length_selected_items=Linker.objects.none()
    for i in length_selection:
        if i=='Short':     
            length_selected_items=length_selected_items|Linker.objects.filter(length__lte=5)
        if i=='Medium':
            length_selected_items=length_selected_items|Linker.objects.filter(length__range=(6,12))
        if i=='Long':
            length_selected_items=length_selected_items|Linker.objects.filter(length__gte=12)
 
    filtered_list=Linker.objects.none()
    for item in length_selected_items:
        filtered_list=filtered_list|Linker.objects.filter(id__iexact=item.id)

    return filtered_list

def flexselect(flexibility_selection):
    flex_selected_items=flexibility.objects.none()
    for i in flexibility_selection:
        if i=='Flexible':
            flex_selected_items=flex_selected_items|flexibility.objects.filter(type__iexact='flexible') 
        if i=='Intermediate':
            flex_selected_items=flex_selected_items|flexibility.objects.filter(type__iexact='context dependent (can be either flexible or rigid)')
        if i=='Rigid':
            flex_selected_items=flex_selected_items|flexibility.objects.filter(type__iexact='rigid')
    filtered_list=Linker.objects.none()
    for item in flex_selected_items:
        filtered_list=filtered_list|Linker.objects.filter(id__iexact=item.id)
    
    return filtered_list

def hydroselect(hydro_slection):
    hydrophobicity_items=Hydrophobicity.objects.none()
    for i in hydro_slection:
        if i=='Extremely Hydrophobic':
            hydrophobicity_items=hydrophobicity_items|Hydrophobicity.objects.filter(gravy_score__gt=1) 
        if i=='Hydrophobic':
            hydrophobicity_items=hydrophobicity_items|Hydrophobicity.objects.filter(gravy_score__range=(0.5,1))
        if i=='Moderate':
            hydrophobicity_items=hydrophobicity_items|Hydrophobicity.objects.filter(gravy_score__range=(-0.5,0.5)) 
        if i=='Hydrophilic':
            hydrophobicity_items=hydrophobicity_items|Hydrophobicity.objects.filter(gravy_score__range=(-1,-0.5)) 
        if i=='Extremely Hydrophilic':
            hydrophobicity_items=hydrophobicity_items|Hydrophobicity.objects.filter(gravy_score__lt=-1)

    filtered_list = Linker.objects.none() 
    for item in hydrophobicity_items:
        filtered_list=filtered_list |Linker.objects.filter(id__iexact=item.id)
    return filtered_list
                
def multiselect(request):
    if request.method=='POST':
        length_selection=request.POST.getlist('lengths')
        flexibility_selection=request.POST.getlist('Flexibility')
        hydrophobicity_selection=request.POST.getlist('Hydrophobicity')
    else:
        length_selection=[]
        flexibility_selection=[]
        hydrophobicity_selection=[]
    
    
    length_selected_items=Linker.objects.none()
    if len(length_selection)>0:
        length_selected_items=lengthselect(length_selection)
        print(length_selected_items)

    if len(flexibility_selection)>0:
        flex_selected_items=flexselect(flexibility_selection)
        print(flex_selected_items)

    if len(hydrophobicity_selection)>0:
        hydrophobicity_items=hydroselect(hydrophobicity_selection)
        print(hydrophobicity_items)
    

    queryset=length_selected_items.intersection(flex_selected_items)
    queryset=queryset.intersection(hydrophobicity_items)

    context = {
        'selected_items': queryset
    }

    return render(request,'results.html',context)

def backbone_dyna(seq):
    url = 'https://bio2byte.be/msatools/api/'
    token = "flexibility"
    #values = {'tool_list': ['dynamine'], 'token': token}

    r = requests.post(url, data={1: seq})
    queue_url = json.loads(r.content.decode("utf-8"))['Location']
    queue_status_url = 'https://bio2byte.be/msatools' + queue_url

    while True:
        response = requests.get(queue_status_url)
        if response.status_code == 200:
            response = requests.get(queue_status_url)
            r=response.json()
            #print("HTTP Status: 200 OK")
            break  # Exit the loop once status is 200
        else:
            #print(f"HTTP Status: {response.status_code}")
            time.sleep(10)  # Delay for 10 seconds before checking again

    backbone=r['results'][0]['backbone']
    average=sum(backbone)/len(backbone)
    results={'backbone':str(backbone),'average':average}

    return results

# Given functions hydrophobicity_calculator and hydrophobicity_distribution
def hydrophobicity_calculator(sequence, ph_env):
    # Acidic Environment (pH2)
    hydrophobicity_1a = {"L":100, "I":100, "F":92, "W":84, "V":79, "M":74}
    hydrophobicity_2a = {"C":52, "Y":49, "A":47}
    hydrophobicity_3a = {"T":13, "E":8, "G":0, "S":-7, "Q":-18, "D":-18}
    hydrophobicity_4a = {"R":-26, "K":-37, "N":-41, "H":-42, "P":-46}

    # Neutral Environment (pH7)
    hydrophobicity_1n = {"F":100, "I":99, "W":97, "L":97, "V":76, "M":74}
    hydrophobicity_2n = {"Y":63, "C":49, "A":41}
    hydrophobicity_3n = {"T":13, "H":8, "G":0, "S":-7, "Q":-10}
    hydrophobicity_4n = {"R":-14, "K":-23, "N":-28, "P":-46, "D":-55}

    i = 0
    vhydrophobic = 0
    hydrophobic = 0
    neutral = 0

linkers_website/apps/contact/views.py
# import bleach
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from django.core.mail import send_mail
from linkers_website import settings


from .forms import ContactForm

# Request made by user to access contacts.html
def contact(request: HttpRequest) -> HttpResponse: 
    
    if request.method == "GET":
        form = ContactForm()
    elif request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            # extract validated fields from form
            bleach.clean(name = form.cleaned_data["name"])
            bleach.clean(email = form.cleaned_data["email"])
            bleach.clean(message = form.cleaned_data["message"])
            send_mail(f"{name} sent an email", message, email, [settings.DEFAULT_FROM_EMAIL])
            return render(request, "contact.html", {"form": form, "success": True})
    else:
        raise NotImplementedError
    
    return render(request, "contact.html", {"form": form})

# post request to recieve data from the server

linkers_website/apps/test2/views.py
# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect
from .models import testdata
from django.http import HttpResponseRedirect
from django.http import HttpResponse
import sys
import json
import pandas as pd
from plotly.offline import plot
import plotly.express as px
import plotly.graph_objects as go
import ast
import pandas as pd



def searchdata(request):
    if request.method=="POST":
        searched=request.POST['searched']
        #query=request.GET.get('searched')
        data=testdata.objects.filter(id__contains=searched)

        return render(request, 'searchresults.html', {'searched':searched,'data':data})
    else:
         return render(request, 'test2.html', {})


        
#, id="1qhaA_1"
def graph_data(request,id):

    #query=request.GET.get('q','')
    #search_results=testdata.objects.filter(name__icontains=query)
    
   
    # Query the specific data based on the ID string
    data_instance = testdata.objects.get(id=id)
    sequence_list=data_instance.Sequence
    char_list_str = data_instance.backbone  # Assuming the values are separated by commas
    char_list = ast.literal_eval(char_list_str)

    # Convert char list to numbers
    numbers_list = [float(value) for value in char_list]

    # Create a Plotly graph
        

    index_list=[]
    for i in range(1,len(sequence_list)):
        index=sequence_list[i-1]+str(i)
        index_list.append(index)

    df=pd.DataFrame(list(zip(index_list,char_list)),columns=['residue index','S^2'])
    df = df.reset_index(drop=True)

    fig=px.line(df, x='residue index', y="S^2")

    fig.update_layout(title='Backbone Dynamic',yaxis_range=[df['S^2'][0]-0.2,1])

    

    fig.add_shape(type="rect",
              x0=df['residue index'][0], y0=0.69,
              x1=df['residue index'][len(df)-1], y1=0.8,
              fillcolor='rgba(0, 255, 0, 0.3)',
              line=dict(color='rgba(0, 0, 0, 0)'))

    # Add the annotation outside the graph
    fig.add_annotation(
        xref='paper', x=0,  # Position the annotation outside the left side of the graph
        yref='paper', y=1,  # Position the annotation at the top of the graph
        text="Rigid",  # Text of the annotation
        showarrow=False,  # Hide the arrow
        font=dict(color='black', size=15)  # Font style
    )

    # Add the annotation outside the graph
    fig.add_annotation(
        xref='paper', x=0,  # Position the annotation outside the left side of the graph
        yref='paper', y=0,  # Position the annotation at the top of the graph
        text="Flexible",  # Text of the annotation
        showarrow=False,  # Hide the arrow
        font=dict(color='black', size=15)  # Font style
    )

    # Add the annotation outside the graph
    fig.add_annotation(
        x=index_list[1],  # Position the annotation outside the left side of the graph
        y=0.75,  # Position the annotation at the top of the graph
        text="Context Dependent",  # Text of the annotation
        showarrow=False,  # Hide the arrow
        font=dict(color='black', size=15)  # Font style
    )

    #pass to the template
    dynamic_plot=plot(fig, output_type="div")
    context={
        'plot_dyna':dynamic_plot
        
        }
    return render(request,'graph.html', context)

linkers_website/templates/add_venue.html
{% block content %}
    <center>
    <h1>Add Venue</h1>
    <br/><br/>
    {% if submitted %} <!--if submitted is true-->
        <p>Your Venue was Submitted !!</p>

    {% else %}
        <form action="" method="POST">
            {% csrf_token %}

            {{ form.as_p }}

            <input type="submit" value="Submit" class="btn btn-secondary">
        </form>
        
    {% endif %}
    </center>
    

{% endblock %}

linkers_website/templates/form.html
<section class="page-section bg-primary" id="Search">

    <div class="container">

        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0 main-heading">Search Database</h2>

        <br/>

        <center>
            <div class=""><p class="lead masthead-subheading secondary-text">Select your desired properties of linker in the drop down menu or enter the ID</p></div>
        </center>
    
    <!--search by ID-->
    <form id="contactForm" data-sb-form-api-token="API_TOKEN" action="{% url 'Linker:search_results_list' %}" method="get">
        {% csrf_token %}
            <!--<input type="text" name="query">-->
        <div class="input-group pt-5">

            <div class="input-group-prepend">

                <span class="input-group-text">ID</span>

            </div>

            <textarea class="form-control" aria-label="With textarea" type="text" name="query"></textarea>

            <div class="input-group-prepend">
            <button type="submit" class="searchButton">Search</button>
            </div>
        </div>

    </form>


    <!--Search by Selection of Properties-->
    <form method="POST" action="{% url 'Linker:search' %}" >
    {% csrf_token %}
    <div class="row justify-content-center">

        <div class="col-lg-8 col-xl-7">

            <!-- Hydrophobicity -->
            <div class="container p-5">

                <div class="row justify-content-between">


                    <div class="col-lg-4 col-md-4 col-sm-4 my-1">

                        <div class="btn-group d-flex justify-content-center">

                            <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >

                                Length

                            </button>

                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <li>
                                    <a  class="dropdown-item" >
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="Short" id="s" name="lengths"/>
                                            <label class="form-check-label" for="s">Short (2-5 amino acids) </label>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="#">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="Medium" id="m" name="lengths"/>
                                            <label class="form-check-label" for="Checkme2">Moderate (6-12 amino acids)</label>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="#">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="Long" id="l" name="lengths"/>
                                            <label class="form-check-label" for="Checkme3">Long (>=12 amino acids)</label>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                            

                        </div>

                    </div>

                    <div class="col-lg-4 col-md-4 col-sm-4 my-1">

                        <div class="btn-group d-flex justify-content-center">

                            <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                                Hydrophobicity

                            </button>

 
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <li>
                                    <a class="dropdown-item" href="#">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="Extremely Hydrophobic" id="Hydrophobicity" name="Hydrophobicity" />
                                            <label class="form-check-label" for="Checkme1">Extremely Hydrophobic</label>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="#">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="Hydrophobic" id="Hydrophobicity" name="Hydrophobicity"/>
                                            <label class="form-check-label" for="Checkme2">Hydrophobic</label>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="#">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="Moderate" id="Hydrophobicity" name="Hydrophobicity"/>
                                            <label class="form-check-label" for="Checkme3">Moderate</label>
                                        </div>
                                    </a>
                                </li>
                                
                                <li>
                                    <a class="dropdown-item" href="#">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="Hydrophilic" id="Hydrophobicity" name="Hydrophobicity" />
                                            <label class="form-check-label" for="Checkme4">Hydrophilic</label>
                                        </div>
                                    </a>
                                </li>

                                <li>
                                    <a class="dropdown-item" href="#">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="Extremely Hydrophilic" id="Hydrophobicity" name="Hydrophobicity" />
                                            <label class="form-check-label" for="Checkme4">Extremely Hydrophilic</label>
                                        </div>
                                    </a>
                                </li>
                            </ul>

                        </div>

                    </div>

                    <div class="col-lg-4 col-md-4 col-sm-4 my-1">

                        <div class="btn-group d-flex justify-content-center">

                            <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                                Flexibility

                            </button>


                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <li>
                                    <a class="dropdown-item" href="#">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="Flexible" id="f" name="Flexibility"/>
                                            <label class="form-check-label" for="f">flexible</label>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="#">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="Intermediate" id="I" name="Flexibility"/>
                                            <label class="form-check-label" for="I">Context Dependent (can be either flexible or rigid)</label>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="#">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="Rigid" id="r" name="Flexibility"/>
                                            <label class="form-check-label" for="r">Rigid</label>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </div>

                    </div>
                    

                </div>

            </div>




            <!-- Submit success message -->

            <!---->

            <!-- This is what your users will see when the form-->

            <!-- has successfully submitted-->

             <!-- <div class="d-none" id="submitSuccessMessage">

                <div class="text-center mb-3">

                    <div class="fw-bolder">Form submission successful!</div>

                    To activate this form, sign up at

                    <br />

                    <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>

                </div>

            </div>

            <!-- Submit error message-->

            <!---->

            <!-- This is what your users will see when there is-->

            <!-- an error submitting the form-->

            <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>

            <!-- Submit Button-->
            <center>
            <button class="btn btn-primary btn-xl" id="submitButton" type="submit" value="Search">Search</button>
            </center>

                       
    </form>

        </div>

        </div>

    </div>

</section>

linkers_website/templates/navbar.html
{% load static %}
<!-- Navigation-->
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top px-2" id="mainNav">
    <div class="container">
        {% url 'public:index' as index_url %}
        <a class="navbar-brand" href="{{index_url}}">LINKED</a>
        <img id="lockicon" src="../static/images/lock.png" alt="Lock">
        <button class="navbar-toggler text-uppercase rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto">
                {% url 'public:index' as index_url %}
                <li class="nav-item mx-0 my-1 mx-lg-1"><a class="nav-link py-3 px-2 px-lg-3 rounded-3 {% if request.path == index_url %}active{% endif %}" href="{{index_url}}">Home</a></li>
                {% url 'calculator:calculator' as calculator_url %}
                <li class="nav-item mx-0 my-1 mx-lg-1"><a class="nav-link py-3 px-2 px-lg-3 rounded-3 {% if request.path == calculator_url %}active{% endif %}" href="{{calculator_url}}">Calculator</a></li>
                {% url 'public:about' as about_url %}
                <li class="nav-item mx-0 my-1 mx-lg-1"><a class="nav-link py-3 px-2 px-lg-3 rounded-3 {% if request.path == about_url %}active{% endif %}" href="{{about_url}}">About Linker</a></li>
                {% url 'Linker:addlinker' as addlinker_url %}
                <li class="nav-item mx-0 my-1 mx-lg-1"><a class="nav-link py-3 px-2 px-lg-3 rounded-3 {% if request.path == addlinker_url %}active{% endif %}" href="{{addlinker_url}}">Submit</a></li>
            
            </ul>
        </div>
    </div>
</nav>

linkers_website/templates/results.html
<!-- search_results.html -->
<!-- Inherit contents of template-->
{% extends 'base.html' %}

{% block content %}

<section class="masthead results-list bg-primary">
    <!-- Linker Details Section-->
    <div class="container">
        <!-- Details Section Heading-->
        <h2 class="page-section-heading text-center text-uppercase text-white">Search Results</h2>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <div>
            <!-- Linker List Section Content-->
            <div class="row">
                <ul>
                    {% for linker in selected_items %}
                        <li>
                            <a href="{% url 'Linker:linker_sequence' idurl=linker.id %}"> {{ linker.id }} </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</section>
{% endblock %}